# Use Tomcat 10 with JDK 21
FROM tomcat:10.1.49-jdk21

# Remove default Tomcat applications (good practice)
RUN rm -rf /usr/local/tomcat/webapps/*

# Copy WAR file generated by Maven into Tomcat
COPY target/*.war /usr/local/tomcat/webapps/simple-website.war

# Expose Tomcat port
EXPOSE 8080
